### ISSUE TITLE
Inputs for min max values

### ISSUE THREAD

**Issue by seghier** [arup-group/Custom-Grasshopper-UI-Components#2]
Hello, thank you very much for this examples
I add 2 inputs to change min/max values of the sliders but i don't find a way to change them on the slider

![image](https://user-images.githubusercontent.com/6026588/184774045-822c4725-cce6-42bf-8c79-b303d287ca0b.png)

Is that possible?

**Comment by kpne** [comment]
Sorry this is a bit late reply! 
You can double-click the "dot" on the slider to bring up the normal Grasshopper slider settings
